//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gymAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaposlenik
    {
        public int Id_Zaposlenik { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Korisnicko_ime { get; set; }
        public string Lozinka { get; set; }
        public string Spol { get; set; }
        public string Email { get; set; }
        public string Broj_mobitela { get; set; }
        public string OIB { get; set; }
        public System.DateTime Datum_zaposlenja { get; set; }
        public int Id_VrstaZaposlenika { get; set; }
    
        public virtual Vrsta_zaposlenika Vrsta_zaposlenika { get; set; }
    }
}
