//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gymAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clanarina
    {
        public int Id_Clanarina { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public int Trajanje { get; set; }
        public double Cijena { get; set; }
    }
}
