//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gymAdmin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clanarina> Clanarina { get; set; }
        public virtual DbSet<Klijent> Klijent { get; set; }
        public virtual DbSet<Mjerenje> Mjerenje { get; set; }
        public virtual DbSet<Vrsta_zaposlenika> Vrsta_zaposlenika { get; set; }
        public virtual DbSet<Zaposlenik> Zaposlenik { get; set; }
    }
}
