//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gymAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klijent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klijent()
        {
            this.Mjerenje = new HashSet<Mjerenje>();
        }
    
        public int Id_Klijent { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Spol { get; set; }
        public string Email { get; set; }
        public string Broj_mobitela { get; set; }
        public System.DateTime Datum_uclanjenja { get; set; }
        public Nullable<int> Id_Clanarina { get; set; }
        public Nullable<System.DateTime> Datum_isteka_clanarine { get; set; }
    
        public virtual Clanarina Clanarina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mjerenje> Mjerenje { get; set; }
    }
}
